name: transparent_image_button
description: This package is used to click on Transparent Image as a Gesture, but it's OnTap function works only when it was clicked on the image or photo itself not on the transparent parts.
version: 1.0.0
homepage: https://github.com/ShadyBoshra2012/flutter_transparent_image_button

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  image: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
